[package]
name = "mbus-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.29.0"
bytes = "1.4.0"
serde = "1.0.152"
serde_json = "1.0.93"
tokio = "1.25.0"
tracing = "0.1.37"
uuid = { version = "1.3.0", features = ["v4"] }
async-trait = "0.1.64"
futures = "0.3.26"
snafu = "0.7.4"
